// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package auto_scaling_group

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AvailabilityZoneDistribution, b.ko.Spec.AvailabilityZoneDistribution) {
		delta.Add("Spec.AvailabilityZoneDistribution", a.ko.Spec.AvailabilityZoneDistribution, b.ko.Spec.AvailabilityZoneDistribution)
	} else if a.ko.Spec.AvailabilityZoneDistribution != nil && b.ko.Spec.AvailabilityZoneDistribution != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy, b.ko.Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy) {
			delta.Add("Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy", a.ko.Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy, b.ko.Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy)
		} else if a.ko.Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy != nil && b.ko.Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy != nil {
			if *a.ko.Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy != *b.ko.Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy {
				delta.Add("Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy", a.ko.Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy, b.ko.Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.AvailabilityZoneImpairmentPolicy, b.ko.Spec.AvailabilityZoneImpairmentPolicy) {
		delta.Add("Spec.AvailabilityZoneImpairmentPolicy", a.ko.Spec.AvailabilityZoneImpairmentPolicy, b.ko.Spec.AvailabilityZoneImpairmentPolicy)
	} else if a.ko.Spec.AvailabilityZoneImpairmentPolicy != nil && b.ko.Spec.AvailabilityZoneImpairmentPolicy != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior, b.ko.Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior) {
			delta.Add("Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior", a.ko.Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior, b.ko.Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior)
		} else if a.ko.Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior != nil && b.ko.Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior != nil {
			if *a.ko.Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior != *b.ko.Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior {
				delta.Add("Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior", a.ko.Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior, b.ko.Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled, b.ko.Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled) {
			delta.Add("Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled", a.ko.Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled, b.ko.Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled)
		} else if a.ko.Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled != nil && b.ko.Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled != nil {
			if *a.ko.Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled != *b.ko.Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled {
				delta.Add("Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled", a.ko.Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled, b.ko.Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled)
			}
		}
	}
	if len(a.ko.Spec.AvailabilityZones) != len(b.ko.Spec.AvailabilityZones) {
		delta.Add("Spec.AvailabilityZones", a.ko.Spec.AvailabilityZones, b.ko.Spec.AvailabilityZones)
	} else if len(a.ko.Spec.AvailabilityZones) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.AvailabilityZones, b.ko.Spec.AvailabilityZones) {
			delta.Add("Spec.AvailabilityZones", a.ko.Spec.AvailabilityZones, b.ko.Spec.AvailabilityZones)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.CapacityRebalance, b.ko.Spec.CapacityRebalance) {
		delta.Add("Spec.CapacityRebalance", a.ko.Spec.CapacityRebalance, b.ko.Spec.CapacityRebalance)
	} else if a.ko.Spec.CapacityRebalance != nil && b.ko.Spec.CapacityRebalance != nil {
		if *a.ko.Spec.CapacityRebalance != *b.ko.Spec.CapacityRebalance {
			delta.Add("Spec.CapacityRebalance", a.ko.Spec.CapacityRebalance, b.ko.Spec.CapacityRebalance)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.CapacityReservationSpecification, b.ko.Spec.CapacityReservationSpecification) {
		delta.Add("Spec.CapacityReservationSpecification", a.ko.Spec.CapacityReservationSpecification, b.ko.Spec.CapacityReservationSpecification)
	} else if a.ko.Spec.CapacityReservationSpecification != nil && b.ko.Spec.CapacityReservationSpecification != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.CapacityReservationSpecification.CapacityReservationPreference, b.ko.Spec.CapacityReservationSpecification.CapacityReservationPreference) {
			delta.Add("Spec.CapacityReservationSpecification.CapacityReservationPreference", a.ko.Spec.CapacityReservationSpecification.CapacityReservationPreference, b.ko.Spec.CapacityReservationSpecification.CapacityReservationPreference)
		} else if a.ko.Spec.CapacityReservationSpecification.CapacityReservationPreference != nil && b.ko.Spec.CapacityReservationSpecification.CapacityReservationPreference != nil {
			if *a.ko.Spec.CapacityReservationSpecification.CapacityReservationPreference != *b.ko.Spec.CapacityReservationSpecification.CapacityReservationPreference {
				delta.Add("Spec.CapacityReservationSpecification.CapacityReservationPreference", a.ko.Spec.CapacityReservationSpecification.CapacityReservationPreference, b.ko.Spec.CapacityReservationSpecification.CapacityReservationPreference)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget, b.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget) {
			delta.Add("Spec.CapacityReservationSpecification.CapacityReservationTarget", a.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget, b.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget)
		} else if a.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget != nil && b.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget != nil {
			if len(a.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs) != len(b.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs) {
				delta.Add("Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs", a.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs, b.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs)
			} else if len(a.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs) > 0 {
				if !ackcompare.SliceStringPEqual(a.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs, b.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs) {
					delta.Add("Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs", a.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs, b.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs)
				}
			}
			if len(a.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs) != len(b.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs) {
				delta.Add("Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs", a.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs, b.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs)
			} else if len(a.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs) > 0 {
				if !ackcompare.SliceStringPEqual(a.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs, b.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs) {
					delta.Add("Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs", a.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs, b.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs)
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DefaultCooldown, b.ko.Spec.DefaultCooldown) {
		delta.Add("Spec.DefaultCooldown", a.ko.Spec.DefaultCooldown, b.ko.Spec.DefaultCooldown)
	} else if a.ko.Spec.DefaultCooldown != nil && b.ko.Spec.DefaultCooldown != nil {
		if *a.ko.Spec.DefaultCooldown != *b.ko.Spec.DefaultCooldown {
			delta.Add("Spec.DefaultCooldown", a.ko.Spec.DefaultCooldown, b.ko.Spec.DefaultCooldown)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DefaultInstanceWarmup, b.ko.Spec.DefaultInstanceWarmup) {
		delta.Add("Spec.DefaultInstanceWarmup", a.ko.Spec.DefaultInstanceWarmup, b.ko.Spec.DefaultInstanceWarmup)
	} else if a.ko.Spec.DefaultInstanceWarmup != nil && b.ko.Spec.DefaultInstanceWarmup != nil {
		if *a.ko.Spec.DefaultInstanceWarmup != *b.ko.Spec.DefaultInstanceWarmup {
			delta.Add("Spec.DefaultInstanceWarmup", a.ko.Spec.DefaultInstanceWarmup, b.ko.Spec.DefaultInstanceWarmup)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DesiredCapacity, b.ko.Spec.DesiredCapacity) {
		delta.Add("Spec.DesiredCapacity", a.ko.Spec.DesiredCapacity, b.ko.Spec.DesiredCapacity)
	} else if a.ko.Spec.DesiredCapacity != nil && b.ko.Spec.DesiredCapacity != nil {
		if *a.ko.Spec.DesiredCapacity != *b.ko.Spec.DesiredCapacity {
			delta.Add("Spec.DesiredCapacity", a.ko.Spec.DesiredCapacity, b.ko.Spec.DesiredCapacity)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DesiredCapacityType, b.ko.Spec.DesiredCapacityType) {
		delta.Add("Spec.DesiredCapacityType", a.ko.Spec.DesiredCapacityType, b.ko.Spec.DesiredCapacityType)
	} else if a.ko.Spec.DesiredCapacityType != nil && b.ko.Spec.DesiredCapacityType != nil {
		if *a.ko.Spec.DesiredCapacityType != *b.ko.Spec.DesiredCapacityType {
			delta.Add("Spec.DesiredCapacityType", a.ko.Spec.DesiredCapacityType, b.ko.Spec.DesiredCapacityType)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.HealthCheckGracePeriod, b.ko.Spec.HealthCheckGracePeriod) {
		delta.Add("Spec.HealthCheckGracePeriod", a.ko.Spec.HealthCheckGracePeriod, b.ko.Spec.HealthCheckGracePeriod)
	} else if a.ko.Spec.HealthCheckGracePeriod != nil && b.ko.Spec.HealthCheckGracePeriod != nil {
		if *a.ko.Spec.HealthCheckGracePeriod != *b.ko.Spec.HealthCheckGracePeriod {
			delta.Add("Spec.HealthCheckGracePeriod", a.ko.Spec.HealthCheckGracePeriod, b.ko.Spec.HealthCheckGracePeriod)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.HealthCheckType, b.ko.Spec.HealthCheckType) {
		delta.Add("Spec.HealthCheckType", a.ko.Spec.HealthCheckType, b.ko.Spec.HealthCheckType)
	} else if a.ko.Spec.HealthCheckType != nil && b.ko.Spec.HealthCheckType != nil {
		if *a.ko.Spec.HealthCheckType != *b.ko.Spec.HealthCheckType {
			delta.Add("Spec.HealthCheckType", a.ko.Spec.HealthCheckType, b.ko.Spec.HealthCheckType)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.InstanceID, b.ko.Spec.InstanceID) {
		delta.Add("Spec.InstanceID", a.ko.Spec.InstanceID, b.ko.Spec.InstanceID)
	} else if a.ko.Spec.InstanceID != nil && b.ko.Spec.InstanceID != nil {
		if *a.ko.Spec.InstanceID != *b.ko.Spec.InstanceID {
			delta.Add("Spec.InstanceID", a.ko.Spec.InstanceID, b.ko.Spec.InstanceID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.InstanceLifecyclePolicy, b.ko.Spec.InstanceLifecyclePolicy) {
		delta.Add("Spec.InstanceLifecyclePolicy", a.ko.Spec.InstanceLifecyclePolicy, b.ko.Spec.InstanceLifecyclePolicy)
	} else if a.ko.Spec.InstanceLifecyclePolicy != nil && b.ko.Spec.InstanceLifecyclePolicy != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers, b.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers) {
			delta.Add("Spec.InstanceLifecyclePolicy.RetentionTriggers", a.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers, b.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers)
		} else if a.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers != nil && b.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers.TerminateHookAbandon, b.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers.TerminateHookAbandon) {
				delta.Add("Spec.InstanceLifecyclePolicy.RetentionTriggers.TerminateHookAbandon", a.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers.TerminateHookAbandon, b.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers.TerminateHookAbandon)
			} else if a.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers.TerminateHookAbandon != nil && b.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers.TerminateHookAbandon != nil {
				if *a.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers.TerminateHookAbandon != *b.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers.TerminateHookAbandon {
					delta.Add("Spec.InstanceLifecyclePolicy.RetentionTriggers.TerminateHookAbandon", a.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers.TerminateHookAbandon, b.ko.Spec.InstanceLifecyclePolicy.RetentionTriggers.TerminateHookAbandon)
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.InstanceMaintenancePolicy, b.ko.Spec.InstanceMaintenancePolicy) {
		delta.Add("Spec.InstanceMaintenancePolicy", a.ko.Spec.InstanceMaintenancePolicy, b.ko.Spec.InstanceMaintenancePolicy)
	} else if a.ko.Spec.InstanceMaintenancePolicy != nil && b.ko.Spec.InstanceMaintenancePolicy != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.InstanceMaintenancePolicy.MaxHealthyPercentage, b.ko.Spec.InstanceMaintenancePolicy.MaxHealthyPercentage) {
			delta.Add("Spec.InstanceMaintenancePolicy.MaxHealthyPercentage", a.ko.Spec.InstanceMaintenancePolicy.MaxHealthyPercentage, b.ko.Spec.InstanceMaintenancePolicy.MaxHealthyPercentage)
		} else if a.ko.Spec.InstanceMaintenancePolicy.MaxHealthyPercentage != nil && b.ko.Spec.InstanceMaintenancePolicy.MaxHealthyPercentage != nil {
			if *a.ko.Spec.InstanceMaintenancePolicy.MaxHealthyPercentage != *b.ko.Spec.InstanceMaintenancePolicy.MaxHealthyPercentage {
				delta.Add("Spec.InstanceMaintenancePolicy.MaxHealthyPercentage", a.ko.Spec.InstanceMaintenancePolicy.MaxHealthyPercentage, b.ko.Spec.InstanceMaintenancePolicy.MaxHealthyPercentage)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.InstanceMaintenancePolicy.MinHealthyPercentage, b.ko.Spec.InstanceMaintenancePolicy.MinHealthyPercentage) {
			delta.Add("Spec.InstanceMaintenancePolicy.MinHealthyPercentage", a.ko.Spec.InstanceMaintenancePolicy.MinHealthyPercentage, b.ko.Spec.InstanceMaintenancePolicy.MinHealthyPercentage)
		} else if a.ko.Spec.InstanceMaintenancePolicy.MinHealthyPercentage != nil && b.ko.Spec.InstanceMaintenancePolicy.MinHealthyPercentage != nil {
			if *a.ko.Spec.InstanceMaintenancePolicy.MinHealthyPercentage != *b.ko.Spec.InstanceMaintenancePolicy.MinHealthyPercentage {
				delta.Add("Spec.InstanceMaintenancePolicy.MinHealthyPercentage", a.ko.Spec.InstanceMaintenancePolicy.MinHealthyPercentage, b.ko.Spec.InstanceMaintenancePolicy.MinHealthyPercentage)
			}
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.InstanceRef, b.ko.Spec.InstanceRef) {
		delta.Add("Spec.InstanceRef", a.ko.Spec.InstanceRef, b.ko.Spec.InstanceRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.LaunchConfigurationName, b.ko.Spec.LaunchConfigurationName) {
		delta.Add("Spec.LaunchConfigurationName", a.ko.Spec.LaunchConfigurationName, b.ko.Spec.LaunchConfigurationName)
	} else if a.ko.Spec.LaunchConfigurationName != nil && b.ko.Spec.LaunchConfigurationName != nil {
		if *a.ko.Spec.LaunchConfigurationName != *b.ko.Spec.LaunchConfigurationName {
			delta.Add("Spec.LaunchConfigurationName", a.ko.Spec.LaunchConfigurationName, b.ko.Spec.LaunchConfigurationName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.LaunchTemplate, b.ko.Spec.LaunchTemplate) {
		delta.Add("Spec.LaunchTemplate", a.ko.Spec.LaunchTemplate, b.ko.Spec.LaunchTemplate)
	} else if a.ko.Spec.LaunchTemplate != nil && b.ko.Spec.LaunchTemplate != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.LaunchTemplate.LaunchTemplateName, b.ko.Spec.LaunchTemplate.LaunchTemplateName) {
			delta.Add("Spec.LaunchTemplate.LaunchTemplateName", a.ko.Spec.LaunchTemplate.LaunchTemplateName, b.ko.Spec.LaunchTemplate.LaunchTemplateName)
		} else if a.ko.Spec.LaunchTemplate.LaunchTemplateName != nil && b.ko.Spec.LaunchTemplate.LaunchTemplateName != nil {
			if *a.ko.Spec.LaunchTemplate.LaunchTemplateName != *b.ko.Spec.LaunchTemplate.LaunchTemplateName {
				delta.Add("Spec.LaunchTemplate.LaunchTemplateName", a.ko.Spec.LaunchTemplate.LaunchTemplateName, b.ko.Spec.LaunchTemplate.LaunchTemplateName)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LaunchTemplate.Version, b.ko.Spec.LaunchTemplate.Version) {
			delta.Add("Spec.LaunchTemplate.Version", a.ko.Spec.LaunchTemplate.Version, b.ko.Spec.LaunchTemplate.Version)
		} else if a.ko.Spec.LaunchTemplate.Version != nil && b.ko.Spec.LaunchTemplate.Version != nil {
			if *a.ko.Spec.LaunchTemplate.Version != *b.ko.Spec.LaunchTemplate.Version {
				delta.Add("Spec.LaunchTemplate.Version", a.ko.Spec.LaunchTemplate.Version, b.ko.Spec.LaunchTemplate.Version)
			}
		}
	}
	if len(a.ko.Spec.LifecycleHookSpecificationList) != len(b.ko.Spec.LifecycleHookSpecificationList) {
		delta.Add("Spec.LifecycleHookSpecificationList", a.ko.Spec.LifecycleHookSpecificationList, b.ko.Spec.LifecycleHookSpecificationList)
	} else if len(a.ko.Spec.LifecycleHookSpecificationList) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.LifecycleHookSpecificationList, b.ko.Spec.LifecycleHookSpecificationList) {
			delta.Add("Spec.LifecycleHookSpecificationList", a.ko.Spec.LifecycleHookSpecificationList, b.ko.Spec.LifecycleHookSpecificationList)
		}
	}
	if len(a.ko.Spec.LoadBalancerNames) != len(b.ko.Spec.LoadBalancerNames) {
		delta.Add("Spec.LoadBalancerNames", a.ko.Spec.LoadBalancerNames, b.ko.Spec.LoadBalancerNames)
	} else if len(a.ko.Spec.LoadBalancerNames) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.LoadBalancerNames, b.ko.Spec.LoadBalancerNames) {
			delta.Add("Spec.LoadBalancerNames", a.ko.Spec.LoadBalancerNames, b.ko.Spec.LoadBalancerNames)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MaxInstanceLifetime, b.ko.Spec.MaxInstanceLifetime) {
		delta.Add("Spec.MaxInstanceLifetime", a.ko.Spec.MaxInstanceLifetime, b.ko.Spec.MaxInstanceLifetime)
	} else if a.ko.Spec.MaxInstanceLifetime != nil && b.ko.Spec.MaxInstanceLifetime != nil {
		if *a.ko.Spec.MaxInstanceLifetime != *b.ko.Spec.MaxInstanceLifetime {
			delta.Add("Spec.MaxInstanceLifetime", a.ko.Spec.MaxInstanceLifetime, b.ko.Spec.MaxInstanceLifetime)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MaxSize, b.ko.Spec.MaxSize) {
		delta.Add("Spec.MaxSize", a.ko.Spec.MaxSize, b.ko.Spec.MaxSize)
	} else if a.ko.Spec.MaxSize != nil && b.ko.Spec.MaxSize != nil {
		if *a.ko.Spec.MaxSize != *b.ko.Spec.MaxSize {
			delta.Add("Spec.MaxSize", a.ko.Spec.MaxSize, b.ko.Spec.MaxSize)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MinSize, b.ko.Spec.MinSize) {
		delta.Add("Spec.MinSize", a.ko.Spec.MinSize, b.ko.Spec.MinSize)
	} else if a.ko.Spec.MinSize != nil && b.ko.Spec.MinSize != nil {
		if *a.ko.Spec.MinSize != *b.ko.Spec.MinSize {
			delta.Add("Spec.MinSize", a.ko.Spec.MinSize, b.ko.Spec.MinSize)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MixedInstancesPolicy, b.ko.Spec.MixedInstancesPolicy) {
		delta.Add("Spec.MixedInstancesPolicy", a.ko.Spec.MixedInstancesPolicy, b.ko.Spec.MixedInstancesPolicy)
	} else if a.ko.Spec.MixedInstancesPolicy != nil && b.ko.Spec.MixedInstancesPolicy != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.MixedInstancesPolicy.InstancesDistribution, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution) {
			delta.Add("Spec.MixedInstancesPolicy.InstancesDistribution", a.ko.Spec.MixedInstancesPolicy.InstancesDistribution, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution)
		} else if a.ko.Spec.MixedInstancesPolicy.InstancesDistribution != nil && b.ko.Spec.MixedInstancesPolicy.InstancesDistribution != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy) {
				delta.Add("Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy", a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy)
			} else if a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy != nil && b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy != nil {
				if *a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy != *b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy {
					delta.Add("Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy", a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity) {
				delta.Add("Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity", a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity)
			} else if a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity != nil && b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity != nil {
				if *a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity != *b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity {
					delta.Add("Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity", a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity) {
				delta.Add("Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity", a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity)
			} else if a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity != nil && b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity != nil {
				if *a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity != *b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity {
					delta.Add("Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity", a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy) {
				delta.Add("Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy", a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy)
			} else if a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy != nil && b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy != nil {
				if *a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy != *b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy {
					delta.Add("Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy", a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools) {
				delta.Add("Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools", a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools)
			} else if a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools != nil && b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools != nil {
				if *a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools != *b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools {
					delta.Add("Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools", a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice) {
				delta.Add("Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice", a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice)
			} else if a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice != nil && b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice != nil {
				if *a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice != *b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice {
					delta.Add("Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice", a.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice, b.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.MixedInstancesPolicy.LaunchTemplate, b.ko.Spec.MixedInstancesPolicy.LaunchTemplate) {
			delta.Add("Spec.MixedInstancesPolicy.LaunchTemplate", a.ko.Spec.MixedInstancesPolicy.LaunchTemplate, b.ko.Spec.MixedInstancesPolicy.LaunchTemplate)
		} else if a.ko.Spec.MixedInstancesPolicy.LaunchTemplate != nil && b.ko.Spec.MixedInstancesPolicy.LaunchTemplate != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification, b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification) {
				delta.Add("Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification", a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification, b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification)
			} else if a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification != nil && b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName, b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName) {
					delta.Add("Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName", a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName, b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName)
				} else if a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName != nil && b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName != nil {
					if *a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName != *b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName {
						delta.Add("Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName", a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName, b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version, b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version) {
					delta.Add("Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version", a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version, b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version)
				} else if a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version != nil && b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version != nil {
					if *a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version != *b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version {
						delta.Add("Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version", a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version, b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version)
					}
				}
			}
			if len(a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.Overrides) != len(b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.Overrides) {
				delta.Add("Spec.MixedInstancesPolicy.LaunchTemplate.Overrides", a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.Overrides, b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.Overrides)
			} else if len(a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.Overrides) > 0 {
				if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.Overrides, b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.Overrides) {
					delta.Add("Spec.MixedInstancesPolicy.LaunchTemplate.Overrides", a.ko.Spec.MixedInstancesPolicy.LaunchTemplate.Overrides, b.ko.Spec.MixedInstancesPolicy.LaunchTemplate.Overrides)
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.NewInstancesProtectedFromScaleIn, b.ko.Spec.NewInstancesProtectedFromScaleIn) {
		delta.Add("Spec.NewInstancesProtectedFromScaleIn", a.ko.Spec.NewInstancesProtectedFromScaleIn, b.ko.Spec.NewInstancesProtectedFromScaleIn)
	} else if a.ko.Spec.NewInstancesProtectedFromScaleIn != nil && b.ko.Spec.NewInstancesProtectedFromScaleIn != nil {
		if *a.ko.Spec.NewInstancesProtectedFromScaleIn != *b.ko.Spec.NewInstancesProtectedFromScaleIn {
			delta.Add("Spec.NewInstancesProtectedFromScaleIn", a.ko.Spec.NewInstancesProtectedFromScaleIn, b.ko.Spec.NewInstancesProtectedFromScaleIn)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PlacementGroup, b.ko.Spec.PlacementGroup) {
		delta.Add("Spec.PlacementGroup", a.ko.Spec.PlacementGroup, b.ko.Spec.PlacementGroup)
	} else if a.ko.Spec.PlacementGroup != nil && b.ko.Spec.PlacementGroup != nil {
		if *a.ko.Spec.PlacementGroup != *b.ko.Spec.PlacementGroup {
			delta.Add("Spec.PlacementGroup", a.ko.Spec.PlacementGroup, b.ko.Spec.PlacementGroup)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ServiceLinkedRoleARN, b.ko.Spec.ServiceLinkedRoleARN) {
		delta.Add("Spec.ServiceLinkedRoleARN", a.ko.Spec.ServiceLinkedRoleARN, b.ko.Spec.ServiceLinkedRoleARN)
	} else if a.ko.Spec.ServiceLinkedRoleARN != nil && b.ko.Spec.ServiceLinkedRoleARN != nil {
		if *a.ko.Spec.ServiceLinkedRoleARN != *b.ko.Spec.ServiceLinkedRoleARN {
			delta.Add("Spec.ServiceLinkedRoleARN", a.ko.Spec.ServiceLinkedRoleARN, b.ko.Spec.ServiceLinkedRoleARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ServiceLinkedRoleRef, b.ko.Spec.ServiceLinkedRoleRef) {
		delta.Add("Spec.ServiceLinkedRoleRef", a.ko.Spec.ServiceLinkedRoleRef, b.ko.Spec.ServiceLinkedRoleRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SkipZonalShiftValidation, b.ko.Spec.SkipZonalShiftValidation) {
		delta.Add("Spec.SkipZonalShiftValidation", a.ko.Spec.SkipZonalShiftValidation, b.ko.Spec.SkipZonalShiftValidation)
	} else if a.ko.Spec.SkipZonalShiftValidation != nil && b.ko.Spec.SkipZonalShiftValidation != nil {
		if *a.ko.Spec.SkipZonalShiftValidation != *b.ko.Spec.SkipZonalShiftValidation {
			delta.Add("Spec.SkipZonalShiftValidation", a.ko.Spec.SkipZonalShiftValidation, b.ko.Spec.SkipZonalShiftValidation)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if len(a.ko.Spec.TargetGroupARNs) != len(b.ko.Spec.TargetGroupARNs) {
		delta.Add("Spec.TargetGroupARNs", a.ko.Spec.TargetGroupARNs, b.ko.Spec.TargetGroupARNs)
	} else if len(a.ko.Spec.TargetGroupARNs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.TargetGroupARNs, b.ko.Spec.TargetGroupARNs) {
			delta.Add("Spec.TargetGroupARNs", a.ko.Spec.TargetGroupARNs, b.ko.Spec.TargetGroupARNs)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.TargetGroupRefs, b.ko.Spec.TargetGroupRefs) {
		delta.Add("Spec.TargetGroupRefs", a.ko.Spec.TargetGroupRefs, b.ko.Spec.TargetGroupRefs)
	}
	if len(a.ko.Spec.TerminationPolicies) != len(b.ko.Spec.TerminationPolicies) {
		delta.Add("Spec.TerminationPolicies", a.ko.Spec.TerminationPolicies, b.ko.Spec.TerminationPolicies)
	} else if len(a.ko.Spec.TerminationPolicies) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.TerminationPolicies, b.ko.Spec.TerminationPolicies) {
			delta.Add("Spec.TerminationPolicies", a.ko.Spec.TerminationPolicies, b.ko.Spec.TerminationPolicies)
		}
	}
	if len(a.ko.Spec.TrafficSources) != len(b.ko.Spec.TrafficSources) {
		delta.Add("Spec.TrafficSources", a.ko.Spec.TrafficSources, b.ko.Spec.TrafficSources)
	} else if len(a.ko.Spec.TrafficSources) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.TrafficSources, b.ko.Spec.TrafficSources) {
			delta.Add("Spec.TrafficSources", a.ko.Spec.TrafficSources, b.ko.Spec.TrafficSources)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.VPCZoneIdentifier, b.ko.Spec.VPCZoneIdentifier) {
		delta.Add("Spec.VPCZoneIdentifier", a.ko.Spec.VPCZoneIdentifier, b.ko.Spec.VPCZoneIdentifier)
	} else if a.ko.Spec.VPCZoneIdentifier != nil && b.ko.Spec.VPCZoneIdentifier != nil {
		if *a.ko.Spec.VPCZoneIdentifier != *b.ko.Spec.VPCZoneIdentifier {
			delta.Add("Spec.VPCZoneIdentifier", a.ko.Spec.VPCZoneIdentifier, b.ko.Spec.VPCZoneIdentifier)
		}
	}

	return delta
}
