// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package auto_scaling_group

import (
	"context"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"

	ec2apitypes "github.com/aws-controllers-k8s/ec2-controller/apis/v1alpha1"
	elbv2apitypes "github.com/aws-controllers-k8s/elbv2-controller/apis/v1alpha1"
	iamapitypes "github.com/aws-controllers-k8s/iam-controller/apis/v1alpha1"
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	acktypes "github.com/aws-controllers-k8s/runtime/pkg/types"

	svcapitypes "github.com/aws-controllers-k8s/autoscaling-controller/apis/v1alpha1"
)

// +kubebuilder:rbac:groups=ec2.services.k8s.aws,resources=instances,verbs=get;list
// +kubebuilder:rbac:groups=ec2.services.k8s.aws,resources=instances/status,verbs=get;list

// +kubebuilder:rbac:groups=ec2.services.k8s.aws,resources=launchtemplates,verbs=get;list
// +kubebuilder:rbac:groups=ec2.services.k8s.aws,resources=launchtemplates/status,verbs=get;list

// +kubebuilder:rbac:groups=iam.services.k8s.aws,resources=roles,verbs=get;list
// +kubebuilder:rbac:groups=iam.services.k8s.aws,resources=roles/status,verbs=get;list

// +kubebuilder:rbac:groups=ec2.services.k8s.aws,resources=launchtemplates,verbs=get;list
// +kubebuilder:rbac:groups=ec2.services.k8s.aws,resources=launchtemplates/status,verbs=get;list

// +kubebuilder:rbac:groups=iam.services.k8s.aws,resources=roles,verbs=get;list
// +kubebuilder:rbac:groups=iam.services.k8s.aws,resources=roles/status,verbs=get;list

// +kubebuilder:rbac:groups=elbv2.services.k8s.aws,resources=targetgroups,verbs=get;list
// +kubebuilder:rbac:groups=elbv2.services.k8s.aws,resources=targetgroups/status,verbs=get;list

// ClearResolvedReferences removes any reference values that were made
// concrete in the spec. It returns a copy of the input AWSResource which
// contains the original *Ref values, but none of their respective concrete
// values.
func (rm *resourceManager) ClearResolvedReferences(res acktypes.AWSResource) acktypes.AWSResource {
	ko := rm.concreteResource(res).ko.DeepCopy()

	if ko.Spec.InstanceRef != nil {
		ko.Spec.InstanceID = nil
	}

	if ko.Spec.LaunchTemplate != nil {
		if ko.Spec.LaunchTemplate.LaunchTemplateRef != nil {
			ko.Spec.LaunchTemplate.LaunchTemplateID = nil
		}
	}

	for f0idx, f0iter := range ko.Spec.LifecycleHookSpecificationList {
		if f0iter.RoleRef != nil {
			ko.Spec.LifecycleHookSpecificationList[f0idx].RoleARN = nil
		}
	}

	if ko.Spec.MixedInstancesPolicy != nil {
		if ko.Spec.MixedInstancesPolicy.LaunchTemplate != nil {
			if ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification != nil {
				if ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateRef != nil {
					ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateID = nil
				}
			}
		}
	}

	if ko.Spec.ServiceLinkedRoleRef != nil {
		ko.Spec.ServiceLinkedRoleARN = nil
	}

	if len(ko.Spec.TargetGroupRefs) > 0 {
		ko.Spec.TargetGroupARNs = nil
	}

	return &resource{ko}
}

// ResolveReferences finds if there are any Reference field(s) present
// inside AWSResource passed in the parameter and attempts to resolve those
// reference field(s) into their respective target field(s). It returns a
// copy of the input AWSResource with resolved reference(s), a boolean which
// is set to true if the resource contains any references (regardless of if
// they are resolved successfully) and an error if the passed AWSResource's
// reference field(s) could not be resolved.
func (rm *resourceManager) ResolveReferences(
	ctx context.Context,
	apiReader client.Reader,
	res acktypes.AWSResource,
) (acktypes.AWSResource, bool, error) {
	ko := rm.concreteResource(res).ko

	resourceHasReferences := false
	err := validateReferenceFields(ko)
	if fieldHasReferences, err := rm.resolveReferenceForInstanceID(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForLaunchTemplate_LaunchTemplateID(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForLifecycleHookSpecificationList_RoleARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForMixedInstancesPolicy_LaunchTemplate_LaunchTemplateSpecification_LaunchTemplateID(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForServiceLinkedRoleARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForTargetGroupARNs(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	return &resource{ko}, resourceHasReferences, err
}

// validateReferenceFields validates the reference field and corresponding
// identifier field.
func validateReferenceFields(ko *svcapitypes.AutoScalingGroup) error {

	if ko.Spec.InstanceRef != nil && ko.Spec.InstanceID != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("InstanceID", "InstanceRef")
	}

	if ko.Spec.LaunchTemplate != nil {
		if ko.Spec.LaunchTemplate.LaunchTemplateRef != nil && ko.Spec.LaunchTemplate.LaunchTemplateID != nil {
			return ackerr.ResourceReferenceAndIDNotSupportedFor("LaunchTemplate.LaunchTemplateID", "LaunchTemplate.LaunchTemplateRef")
		}
	}

	for _, f0iter := range ko.Spec.LifecycleHookSpecificationList {
		if f0iter.RoleRef != nil && f0iter.RoleARN != nil {
			return ackerr.ResourceReferenceAndIDNotSupportedFor("LifecycleHookSpecificationList.RoleARN", "LifecycleHookSpecificationList.RoleRef")
		}
	}

	if ko.Spec.MixedInstancesPolicy != nil {
		if ko.Spec.MixedInstancesPolicy.LaunchTemplate != nil {
			if ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification != nil {
				if ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateRef != nil && ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateID != nil {
					return ackerr.ResourceReferenceAndIDNotSupportedFor("MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateID", "MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateRef")
				}
			}
		}
	}

	if ko.Spec.ServiceLinkedRoleRef != nil && ko.Spec.ServiceLinkedRoleARN != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("ServiceLinkedRoleARN", "ServiceLinkedRoleRef")
	}

	if len(ko.Spec.TargetGroupRefs) > 0 && len(ko.Spec.TargetGroupARNs) > 0 {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("TargetGroupARNs", "TargetGroupRefs")
	}
	return nil
}

// resolveReferenceForInstanceID reads the resource referenced
// from InstanceRef field and sets the InstanceID
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForInstanceID(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.AutoScalingGroup,
) (hasReferences bool, err error) {
	if ko.Spec.InstanceRef != nil && ko.Spec.InstanceRef.From != nil {
		hasReferences = true
		arr := ko.Spec.InstanceRef.From
		if arr.Name == nil || *arr.Name == "" {
			return hasReferences, fmt.Errorf("provided resource reference is nil or empty: InstanceRef")
		}
		namespace := ko.ObjectMeta.GetNamespace()
		if arr.Namespace != nil && *arr.Namespace != "" {
			namespace = *arr.Namespace
		}
		obj := &ec2apitypes.Instance{}
		if err := getReferencedResourceState_Instance(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return hasReferences, err
		}
		ko.Spec.InstanceID = (*string)(obj.Status.InstanceID)
	}

	return hasReferences, nil
}

// getReferencedResourceState_Instance looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Instance(
	ctx context.Context,
	apiReader client.Reader,
	obj *ec2apitypes.Instance,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"Instance",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Instance",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Instance",
			namespace, name)
	}
	if obj.Status.InstanceID == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Instance",
			namespace, name,
			"Status.InstanceID")
	}
	return nil
}

// resolveReferenceForLaunchTemplate_LaunchTemplateID reads the resource referenced
// from LaunchTemplate.LaunchTemplateRef field and sets the LaunchTemplate.LaunchTemplateID
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForLaunchTemplate_LaunchTemplateID(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.AutoScalingGroup,
) (hasReferences bool, err error) {
	if ko.Spec.LaunchTemplate != nil {
		if ko.Spec.LaunchTemplate.LaunchTemplateRef != nil && ko.Spec.LaunchTemplate.LaunchTemplateRef.From != nil {
			hasReferences = true
			arr := ko.Spec.LaunchTemplate.LaunchTemplateRef.From
			if arr.Name == nil || *arr.Name == "" {
				return hasReferences, fmt.Errorf("provided resource reference is nil or empty: LaunchTemplate.LaunchTemplateRef")
			}
			namespace := ko.ObjectMeta.GetNamespace()
			if arr.Namespace != nil && *arr.Namespace != "" {
				namespace = *arr.Namespace
			}
			obj := &ec2apitypes.LaunchTemplate{}
			if err := getReferencedResourceState_LaunchTemplate(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
				return hasReferences, err
			}
			ko.Spec.LaunchTemplate.LaunchTemplateID = (*string)(obj.Status.ID)
		}
	}

	return hasReferences, nil
}

// getReferencedResourceState_LaunchTemplate looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_LaunchTemplate(
	ctx context.Context,
	apiReader client.Reader,
	obj *ec2apitypes.LaunchTemplate,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"LaunchTemplate",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"LaunchTemplate",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"LaunchTemplate",
			namespace, name)
	}
	if obj.Status.ID == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"LaunchTemplate",
			namespace, name,
			"Status.ID")
	}
	return nil
}

// resolveReferenceForLifecycleHookSpecificationList_RoleARN reads the resource referenced
// from LifecycleHookSpecificationList.RoleRef field and sets the LifecycleHookSpecificationList.RoleARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForLifecycleHookSpecificationList_RoleARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.AutoScalingGroup,
) (hasReferences bool, err error) {
	for f0idx, f0iter := range ko.Spec.LifecycleHookSpecificationList {
		if f0iter.RoleRef != nil && f0iter.RoleRef.From != nil {
			hasReferences = true
			arr := f0iter.RoleRef.From
			if arr.Name == nil || *arr.Name == "" {
				return hasReferences, fmt.Errorf("provided resource reference is nil or empty: LifecycleHookSpecificationList.RoleRef")
			}
			namespace := ko.ObjectMeta.GetNamespace()
			if arr.Namespace != nil && *arr.Namespace != "" {
				namespace = *arr.Namespace
			}
			obj := &iamapitypes.Role{}
			if err := getReferencedResourceState_Role(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
				return hasReferences, err
			}
			ko.Spec.LifecycleHookSpecificationList[f0idx].RoleARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
		}
	}

	return hasReferences, nil
}

// getReferencedResourceState_Role looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Role(
	ctx context.Context,
	apiReader client.Reader,
	obj *iamapitypes.Role,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"Role",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Role",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Role",
			namespace, name)
	}
	if obj.Status.ACKResourceMetadata == nil || obj.Status.ACKResourceMetadata.ARN == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Role",
			namespace, name,
			"Status.ACKResourceMetadata.ARN")
	}
	return nil
}

// resolveReferenceForMixedInstancesPolicy_LaunchTemplate_LaunchTemplateSpecification_LaunchTemplateID reads the resource referenced
// from MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateRef field and sets the MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateID
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForMixedInstancesPolicy_LaunchTemplate_LaunchTemplateSpecification_LaunchTemplateID(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.AutoScalingGroup,
) (hasReferences bool, err error) {
	if ko.Spec.MixedInstancesPolicy != nil {
		if ko.Spec.MixedInstancesPolicy.LaunchTemplate != nil {
			if ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification != nil {
				if ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateRef != nil && ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateRef.From != nil {
					hasReferences = true
					arr := ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateRef.From
					if arr.Name == nil || *arr.Name == "" {
						return hasReferences, fmt.Errorf("provided resource reference is nil or empty: MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateRef")
					}
					namespace := ko.ObjectMeta.GetNamespace()
					if arr.Namespace != nil && *arr.Namespace != "" {
						namespace = *arr.Namespace
					}
					obj := &ec2apitypes.LaunchTemplate{}
					if err := getReferencedResourceState_LaunchTemplate(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
						return hasReferences, err
					}
					ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateID = (*string)(obj.Status.ID)
				}
			}
		}
	}

	return hasReferences, nil
}

// resolveReferenceForServiceLinkedRoleARN reads the resource referenced
// from ServiceLinkedRoleRef field and sets the ServiceLinkedRoleARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForServiceLinkedRoleARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.AutoScalingGroup,
) (hasReferences bool, err error) {
	if ko.Spec.ServiceLinkedRoleRef != nil && ko.Spec.ServiceLinkedRoleRef.From != nil {
		hasReferences = true
		arr := ko.Spec.ServiceLinkedRoleRef.From
		if arr.Name == nil || *arr.Name == "" {
			return hasReferences, fmt.Errorf("provided resource reference is nil or empty: ServiceLinkedRoleRef")
		}
		namespace := ko.ObjectMeta.GetNamespace()
		if arr.Namespace != nil && *arr.Namespace != "" {
			namespace = *arr.Namespace
		}
		obj := &iamapitypes.Role{}
		if err := getReferencedResourceState_Role(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return hasReferences, err
		}
		ko.Spec.ServiceLinkedRoleARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
	}

	return hasReferences, nil
}

// resolveReferenceForTargetGroupARNs reads the resource referenced
// from TargetGroupRefs field and sets the TargetGroupARNs
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForTargetGroupARNs(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.AutoScalingGroup,
) (hasReferences bool, err error) {
	for _, f0iter := range ko.Spec.TargetGroupRefs {
		if f0iter != nil && f0iter.From != nil {
			hasReferences = true
			arr := f0iter.From
			if arr.Name == nil || *arr.Name == "" {
				return hasReferences, fmt.Errorf("provided resource reference is nil or empty: TargetGroupRefs")
			}
			namespace := ko.ObjectMeta.GetNamespace()
			if arr.Namespace != nil && *arr.Namespace != "" {
				namespace = *arr.Namespace
			}
			obj := &elbv2apitypes.TargetGroup{}
			if err := getReferencedResourceState_TargetGroup(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
				return hasReferences, err
			}
			if ko.Spec.TargetGroupARNs == nil {
				ko.Spec.TargetGroupARNs = make([]*string, 0, 1)
			}
			ko.Spec.TargetGroupARNs = append(ko.Spec.TargetGroupARNs, (*string)(obj.Status.ACKResourceMetadata.ARN))
		}
	}

	return hasReferences, nil
}

// getReferencedResourceState_TargetGroup looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_TargetGroup(
	ctx context.Context,
	apiReader client.Reader,
	obj *elbv2apitypes.TargetGroup,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"TargetGroup",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"TargetGroup",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"TargetGroup",
			namespace, name)
	}
	if obj.Status.ACKResourceMetadata == nil || obj.Status.ACKResourceMetadata.ARN == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"TargetGroup",
			namespace, name,
			"Status.ACKResourceMetadata.ARN")
	}
	return nil
}
